default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development_ship_packages

test:
  <<: *default
  database: test_ship_packages

production:
  <<: *default
  database: ship_packages_production
  username: ship_packages
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %> 
